apiVersion: apps/v1
kind: Deployment
metadata:
  name: mywebapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mywebapp
  template:
    metadata:
      labels:
        app: mywebapp
    spec:
      containers:
        - name: mywebapp
          image: xublimeregistry.azurecr.io/mywebapp:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
