name: Build and deploy ASP.Net Core app to Azure Web App - xublime-myweapp2

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore mywebapp2/mywebapp2.csproj
      
      - name: Build project
        run: dotnet build mywebapp2/mywebapp2.csproj --configuration Release --no-restore
      
      - name: Publish project
        run: dotnet publish mywebapp2/mywebapp2.csproj -c Release -o ./publish --no-build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-app
          path: ./publish

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: dotnet-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_131981AAB97743BCBABFDF26B4526018 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_7EC0C2DB137E40508C69569B16ABCBE1 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_87854376FA804C788318D86F2BBBDC2A }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'xublime-myweapp2'
          slot-name: 'Production'
          package: ./dotnet-app
